---
name: 'techjavelin/iac-github-actions // terraform // prepare'
description: 'Creates a plan and makes it accessible as outputs and as a binary artifact to be consumed by apply'

branding:
  icon: edit
  color: green

inputs:
  terraform-dir:
    description: "Absolute path or relative path from project root to where your terraform files are"
    required: false
    default: '.'
  artifact-name:
    description: "Customize the name of the artifact" 
    required: false
    default: 'plan-${{ github.sha }}-${{ github.run_id }}-${{ github.run_number }}'
  backend_cloud_credential_token:
    description: "If you're using terraform cloud as a backend, provide your credential here"
    required: false
  workspace_name:
    description: "If you're using workspaces, provide the workspace name here"
    required: false

outputs:
  plan: 
    description: "The plan output"
    value: ${{ steps.plan.outputs.stdout }}
  result:
    description: "The outcome of running plan"
    value: ${{ steps.plan.outcome }}
  artifact:
    description: "The name of the artifact uploaded"
    value: ${{ inputs.artifact-name }}

runs:
  using: composite
  steps:
    - name: terraform // prepare // setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_cloud_credential_hostname: ${{ inputs.terraform-backend-credential-hostname }}
        terraform_cloud_credential_token: ${{ inputs.terraform-backend-credential-token }}

    - name: terraform // prepare // init
      id: init
      run: terraform -chdir=${{ inputs.terraform-dir }} init
      shell: bash

    - name: terraform // prepare // plan
      id: plan
      run: terraform -chdir=${{ inputs.terraform-dir }} plan -out=plan.tfplan -no-color
      shell: bash
      env:
        TF_VAR_terraform_cloud_workspace: ${{ inputs.workspace_name }}
    
    - name: terraform // prepare // upload        
      uses: actions/upload-artifact@v3
      id: upload
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.terraform-dir }}/plan.tfplan
        if-no-files-found: error
